### ISSUE TITLE
Runtime Exceptions

### ISSUE THREAD

**Issue by coolgooze** [chrisboulton/collectd-python-mysql#11]
I followed the documentation and could not make it to work,

Collectd Log-
Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'log'
read-function of plugin `python.mysql' failed. Will suspend it for 120.000 seconds.

Collectd Config-
<LoadPlugin python>
    Globals true
</LoadPlugin>

<Plugin "python">
    ModulePath "/usr/lib/python2.6/site-packages/" 
    Import mysql
    <Module mysql>
    Host "XXXXX"
    User "collectd"
    Password "XXXX"
    Port "3306"
    </Module>
</Plugin>

Additonal-
I am running on RHEL 6 with Mysql 5.7
Installed "yum install python-mysqldb"
copied mysql.py to /usr/lib/python2.6/site-packages/
collectd-mysql-5.5.0-1.el6.x86_64 already installed and latest version

-Local Python error
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import mysql
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.6/site-packages/mysql.py", line 26, in <module>
> > >     import collectd
> > > ImportError: No module named collectd

**Comment by coolgooze** [comment]
`<Plugin "python">
    ModulePath "/usr/lib/python2.6/site-packages/"
    Import mysql
    <Module mysql>
    Host "xxxxx"
    User "collectd"
    Password "XXX"
    Port "3306"
    </Module>
</Plugin>`

uploading config

**Comment by ser** [comment]
I confirm the problem, it's related to innodb stats, when I comment out lines:

https://github.com/chrisboulton/collectd-python-mysql/blob/master/mysql.py#L560-L563

everything works well.
